#!/bin/sh

app=stegfs
version=2015.06
pkgdir=build

mkdir -p ${pkgdir}/usr/{bin,share/man/man1}
make -f Makefile
make -f Makefile install PREFIX=${pkgdir}

mkdir ${pkgdir}/install
cp slack-desc ${pkgdir}/install

cd  ${pkgdir}
makepkg -l y -c n ../${app}-${version}-x86_64-1aa.tgz
