.TH stegfs 1 2014.XX
.SH NAME
\fBstegfs\fR \- A (FUSE based) steganographic file system for Unix-like operating systems
.P
\fBmkstegfs\fR \- mkfs binary to create stegfs file systems
.SH SYNOPSIS
\fBstegfs\fR <\fIfile system\fR> <\fImount point\fR> [\fIFUSE options ...\fR]
.P
\fBmkstegfs\fR <\fB\-s\fR \fIsize\fR> <\fIfile system\fR>
.SH DESCRIPTION
\fBstegfs\fR is a FUSE based file system which provides absolute security. Using
encryption to secure files, and the art of steganography to hide them, stegfs
aims to ensure that the existence of such files isn't guaranteed. Implemented as
a FUSE based file system and using the mhash and mcrypt libraries to provide the
cryptographic hash and symmetric block cipher functions, stegfs is at the
cutting edge of secure file system technology.
.SH OPTIONS \fIstegfs\fR
.TP
.BR \-h ", " \-\-help\fR
Display list of arguments
.TP
.BR \-l ", " \-\-licence\fR
Display GNU GPL v3 licence header
.TP
.BR \-v ", " \-\-version\fR
Display application version
.SH NOTES
It doesn't matter which order the file system and mount point are specified
as stegfs will figure that out. All other options are passed to FUSE.
.P
The FUSE option -s (to use a single thread) is (currently) forced by stegfs.
.SH OPTIONS \fImkstegfs\fR
.TP
.BR \-s\fR " " \fISIZE\fR
Desired file system size, required when creating a file system in a normal file
.TP
.BR \-f\fR
Force overwrite existing file, required when overwriting a file system in a normal file
.TP
.BR \-r\fR
Rewrite the superblock (perhaps it became corrupt)
.SH NOTES
Size option isn't necessary when creating a file system on a block device.
.P
Size are in megabytes unless otherwise told: GB, TB, PB, or EB.
.SH AUTHOR
Written by Ashley Morgan Anderson
.SH BUGS
stegfs is currently single threaded - more work is needed to support mutliple
threads accessing the file system at once. This is force by FUSE.
.P
Although if you do think you've really found a bug, please first check the
README or the CHANGELOG to see if it has already been documented and scheduled
for the next release; then if you're still convinced, let us know at
https://albinoloverats.net/?tracker
.SH COPYRIGHT
Copyright \(co 2004\-2014 albinoloverats ~ Software Development
.SH LICENCE
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.
.PP
Note on spelling: As albinoloverats.net is a British company and \(lqlicence\(rq
is the correct spelling in its native language. However, the name of the
licences, written in most cases in America, feature the American spelling of the
word, license. As part of the title of the official licensing document it was
thought inappropriate to alter the spelling. In British English, license is the
verb, licence is the noun and licensee is the person who is granted a Licence.
